@baseUrl = http://localhost:3333

### 

# @name createLink
POST {{baseUrl}}/links
Content-Type: application/json

{
  "shortUrlSlug": "google-1",
  "originalUrl": "https://google.com"
}


###

# @name getLink
GET {{baseUrl}}/links/google-1