@baseUrl = http://localhost:3333

### 
# @name createLink
POST {{baseUrl}}/links
Content-Type: application/json

{
  "shortUrlSlug": "short-url-slug-1",
  "originalUrl": "https://google.com"
}

###
# @name getLink
GET {{baseUrl}}/links/google-1

###
# @name deleteLink
DELETE {{baseUrl}}/links/google-1

###
# @name getLinks
GET {{baseUrl}}/links

### 
# @name exportLinks
GET {{baseUrl}}/export-links